### ISSUE TITLE
Plugin doesn't properly handle DB_HOST when it contains a non-default unix socket

### ISSUE THREAD

**Issue by josh4trunks** [Ivinco/WordPress-Sphinx-Search-plugin#5]
Hi, I tried setting this plugin up today but hit a few snags. "sphinxsearch_sphinxinstall.php" doesn't seem to know what to do with a 'DB_HOST' like ``localhost:/path/to/mysql.sock``

I think optimal fix is to do something similar to what is done in owncloud here.
https://github.com/owncloud/core/blob/master/lib/private/db/connectionfactory.php#L162
This would need to be done before this line.
https://github.com/Ivinco/WordPress-Sphinx-Search-plugin/blob/master/php/sphinxsearch_sphinxinstall.php#L150

I also noticed that "sphinxsearch_sphinxinstall.php" takes into account PHP's "mysql.default_socket". So to still use that value as a fallback we'll need to put in a bit more logic and be careful with the ordering of code.

I'll work on this sometime soon and submit a pull request.

**Comment by Ivinco** [comment]
Hello Joshua

Thank you for the commit. I've merged it into the branch.

Best wishes,
Sergey

**Comment by josh4trunks** [comment]
Awesome, thanks for taking a look and for merging.
